[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.27"
optimizer = true
optimizer_runs = 200
remappings = [
    "risc0/=lib/risc0-ethereum/contracts/src/",
    "solady/=lib/solady/src/",
    # foundry is not able to detect this particular remapping for some reason...
    "openzeppelin/=lib/risc0-ethereum/lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
